version: '3.3'

services:
  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./database/backup:/backup/
